- name: Install Python3
  hosts: DevOpsBootcamp-servers
  # execute the tasks as a root user
  become: yes
  tasks:
    - name: Install Python3
      # force this task to be executed using python2
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: python3
        # force yum to check if cache is out of date date and redownload if needed.
        update_cache: yes
        # present ensures that a desired package is installed
        # absent or removed ensures the package is remved
        state: present

    - name: install Docker
      # force this task to be executed using python2
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: docker
        update_cache: yes
        state: present

    - name: Install Docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{lookup('pipe','uname -s')}}-{{lookup('pipe', 'uname -m')}}
        # destination of downloaded file
        dest: /usr/local/bin/docker-compose
        # change permission of the downloaded file
        mode: +x

    - name: Start Docker 
      # use system module to start docker 
      systemd:
        name: docker
        state: started

# for ec2-user to pull and run images, you need to add ec2-user to docker group
    - name: Add ec2-user to docker group
      # use user module
      user:
        name: ec2-user
        groups: docker
        # append ec2 to docker group
        append: yes
      # Adding a user to a group only takes effect after reconnecting to the server.
    - name: reconnect to server
      meta: reset_connection


    - name: pip install requrests
      pip:
        name: 
          - requests
          - docker
        state: present



    - name: Run httpd
      docker_container:
        # use variables to define name of a container instead of hard-coding it here
        name: myhttpd
        image: httpd
        # state can be started, absent, stopped or present
        state: started
        ports: 8080:80
    - name: Container status
      docker_container_info:
        name: myhttpd
      register: result
      # check out the result of my container
    - debug: msg={{result.container.State}}

